[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
name = "onefetch-manifest"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0"
cargo_toml = "0.13.0"
npm-package-json = "0.1.3"
strum = { version = "0.24.1", features = ["derive"] }
