[package]
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
name = "onefetch-manifest"
description = "Detect and parse manifest files"

[dependencies]
anyhow.workspace = true
cargo_toml = "0.15.3"
npm-package-json = "0.1.3"
strum.workspace = true
