[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
name = "onefetch-manifest"
description = "Detect and parse manifest files"
version = "2.16.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/o2sh/onefetch"

[dependencies]
anyhow = "1.0"
cargo_toml = "0.14.1"
npm-package-json = "0.1.3"
strum = { version = "0.24.1", features = ["derive"] }
