name: Vercel Deployment CI
on:
  push:
    branches: ["main"]
    paths:
      - "docs/vercel/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/vercel/**"

jobs:
  check:
    name: Check Vercel Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/vercel

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: docs/vercel/package-lock.json

      - name: Install Dependencies
        run: npm ci
      # NOTE Since build is automated by vercel, it's probably
      # redundant to test it here, too
      - name: Svelte Check
        run: npm run check:svelte -- --fail-on-warnings

      - name: ESLint
        run: npm run check:lint

      - name: Prettier
        run: npm run check:prettier
