name: Sync Wiki
on:
  push:
    branches: [main]
    paths:
      - ".github/wiki/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/wiki/**"

  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Sync Wiki

    steps:
      - uses: actions/checkout@v3
      - uses: spenserblack/actions-wiki@v0.1
        with:
          token: ${{ secrets.WIKI_TOKEN }}
