[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
name = "onefetch-image"
version = "2.14.1"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0"
clap = "4.0.26"
image = "0.24.4"

[target.'cfg(not(windows))'.dependencies]
color_quant = "1.1.0"
base64 = "0.13.1"
libc = "0.2.137"
